Repository prgrms-web-devcourse-final-project/WEB1_2_PitchingMate_FE, pull requests merged in 2024-11, with the labels that each got.

#17 ✨ Feat : 알림 아이콘 생성 #2
  src/layouts/Header/index.tsx
  src/layouts/Header/style.ts
Labels: :sparkles: Feat, :rainbow: Design

#18 ✨ Feat : 메이트 카드 작업완료 #4
  src/components/.gitkeep
  src/components/CardBedge/index.tsx
  src/components/CardBedge/style.ts
  src/components/MateCard/index.tsx
  src/components/MateCard/style.ts
  src/components/Placeholder/index.tsx
  src/components/Placeholder/style.ts
Labels: :sparkles: Feat, :recycle: Refactor

#19 ✨ Feat : 굿즈 거래 카드 마크업 + 플레이스홀더 svg 추가 #5
  src/assets/placeholder.svg
  src/components/GoodsCard/index.tsx
  src/components/GoodsCard/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#20 ✨ Feat : 글로벌 버튼 작업완료 #13
  src/components/GlobalButton/index.tsx
  src/components/GlobalButton/style.ts
Labels: :sparkles: Feat

#21 ✨ Feat : 404 페이지 작업완료 #12
  src/pages/ErrorPage/index.tsx
  src/pages/ErrorPage/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#22 ✨ Feat : 서브헤더 마크업 개발 & 알람 아이콘 개별 컴포넌트화 #8
  src/assets/icon/back.svg
  src/components/Alarm/index.tsx
  src/components/Alarm/style.ts
  src/layouts/Header/index.tsx
  src/layouts/Header/style.ts
  src/layouts/SubHeader/index.tsx
  src/layouts/SubHeader/style.ts
  src/layouts/SubLayout/index.tsx
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#23 ✨ Feat : 팀 선택 모달 마크업 완성 #10
  src/components/TeamSelectModal/index.tsx
  src/components/TeamSelectModal/style.ts
Labels: :sparkles: Feat, :rainbow: Design

#24 ✨ Feat : 프로필 뱃지 마크업 #16
  src/assets/default/default_profile.svg
  src/assets/default/placeholder.svg
  src/components/GoodsCard/index.tsx
  src/components/ProfileBedge/index.tsx
  src/components/ProfileBedge/style.ts
  src/layouts/GlobalLayout/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#25 🐛 Fix : 백드롭 클릭 시 모달이 닫히지 않는 문제 해결
  src/components/TeamSelectModal/index.tsx
Labels: :bug: Fix

#26 ✨ Feat : 하단 모달 마크업 #14
  src/components/BottomModal/index.tsx
  src/components/BottomModal/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#27 ✨ Feat : 알럿 창 마크업 #15
  src/components/Alert/index.tsx
  src/components/Alert/style.ts
  src/layouts/GlobalLayout/index.tsx
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#28 ✨ Feat : 입력 폼 마크업 완성
  src/components/Form/index.tsx
  src/components/Form/style.ts
Labels: :sparkles: Feat, :rainbow: Design

#29 ✨ Feat : 팀 선택 섹션 작업완료 #3
  src/components/TeamSelectSection/index.tsx
  src/components/TeamSelectSection/style.ts
  src/layouts/GlobalLayout/index.tsx
  src/utils/kboInfo.tsx
Labels: :sparkles: Feat

#30 ✨ Feat : 알약 버튼 마크업 완료 #7
  src/components/PillButton/index.tsx
  src/components/PillButton/style.ts
  src/components/PillButtonList/index.tsx
  src/components/PillButtonList/style.ts
Labels: :sparkles: Feat, :rainbow: Design

#35 ✨ Feat : 메이트 구인 페이지 마크업 완료 #31
  src/components/BottomModal/index.tsx
  src/components/SubmitPage/index.tsx
  src/components/SubmitPage/style.ts
  src/components/TeamSelectModal/index.tsx
  src/hooks/useTabs.ts
  src/pages/.gitkeep
  src/pages/MatePostingPage/Tabs/FirstTab/BottomModalOption/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/BottomModalOption/style.ts
  src/pages/MatePostingPage/Tabs/FirstTab/GameButtonList/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/GameButtonList/style.ts
  src/pages/MatePostingPage/Tabs/FirstTab/GameList/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/GameList/style.ts
  src/pages/MatePostingPage/Tabs/FirstTab/GameListCard/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/GameListCard/style.ts
  src/pages/MatePostingPage/Tabs/FirstTab/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/style.ts
  src/pages/MatePostingPage/Tabs/SecondTab/index.tsx
  src/pages/MatePostingPage/Tabs/SecondTab/style.ts
  src/pages/MatePostingPage/Tabs/ThirdTab/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/style.ts
  src/pages/MatePostingPage/index.tsx
  src/routes/index.tsx
  src/styles/globalStyle.ts
  src/utils/tabModel.ts
Labels: :sparkles: Feat

#39 ✨ Feat : 프로필 페이지 마크업 #32
  src/assets/default/area.png
  src/assets/icon/link.svg
  src/components/Form/style.ts
  src/layouts/Header/style.ts
  src/layouts/SubHeader/style.ts
  src/pages/FollowPage/FollowBox/index.tsx
  src/pages/FollowPage/index.tsx
  src/pages/FollowPage/style.ts
  src/pages/GoodsRecordPage/GoodsRecordBox/index.tsx
  src/pages/GoodsRecordPage/index.tsx
  src/pages/GoodsRecordPage/style.ts
  src/pages/ProfilePage/ProfileEdit.tsx
  src/pages/ProfilePage/ProfileMain.tsx
  src/pages/ProfilePage/ReviewPage.tsx
  src/pages/ProfilePage/style.ts
  src/pages/TimelinePage/TimelineBox/index.tsx
  src/pages/TimelinePage/index.tsx
  src/pages/TimelinePage/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#37 ✨ Feat : 채팅 페이지 마크업 완료 #31
  src/components/Alert/index.tsx
  src/components/GlobalButton/index.tsx
  src/components/PillButton/index.tsx
  src/components/PillButton/style.ts
  src/components/ProfileBedge/index.tsx
  src/pages/ChatPage/ChatCard/index.tsx
  src/pages/ChatPage/ChatCard/style.ts
  src/pages/ChatPage/index.tsx
  src/pages/ChatPage/style.ts
  src/routes/index.tsx
  src/styles/globalStyle.ts
  src/utils/alertMessage.ts
Labels: :sparkles: Feat

#43 Feat : 굿즈 거래 작성 페이지 마크업 완료
  src/components/SubmitPage/index.tsx
  src/components/SubmitPage/style.ts
  src/hooks/useTeamDialog.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/style.ts
  src/pages/GoodsPostingPage/Tabs/SecondTab/ResultCard/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/ResultCard/style.ts
  src/pages/GoodsPostingPage/Tabs/SecondTab/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/style.ts
  src/pages/GoodsPostingPage/index.tsx
  src/pages/GoodsPostingPage/style.ts
  src/pages/MatePostingPage/Tabs/FirstTab/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/style.ts
  src/pages/MatePostingPage/index.tsx
  src/routes/index.tsx
  src/utils/tabModel.ts
Labels: :sparkles: Feat

#38 Feat/#11 알림 페이지 마크업
  src/components/Alarm/index.tsx
  src/components/PillButton/style.ts
  src/components/PillButtonList/index.tsx
  src/pages/NotificationPage/index.tsx
  src/pages/NotificationPage/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#45 ✨ Feat : 리뷰 작성 페이지 마크업 #42
  src/pages/ReviewWritePage/index.tsx
  src/pages/ReviewWritePage/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#52 ✨ Feat : 채팅 페이지 마크업 완료 #44
  src/assets/icon/message_send.svg
  src/assets/icon/up_black.svg
  src/components/GoodsListCard/index.tsx
  src/components/GoodsListCard/style.ts
  src/components/UserInfoList/index.tsx
  src/components/UserInfoList/style.ts
  src/pages/ChatPage/index.tsx
  src/pages/ChatRoom/ChatCard/index.tsx
  src/pages/ChatRoom/ChatCard/style.ts
  src/pages/ChatRoom/ChatInput/index.tsx
  src/pages/ChatRoom/ChatInput/style.ts
  src/pages/ChatRoom/index.tsx
  src/pages/ChatRoom/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat

#49 Feat/#46 스플래시 페이지 마크업, 로고 & 플레이스 홀더 이미지 수정
  public/PITCHING MATE.svg
  src/assets/default/placeholder.svg
  src/assets/logo/logo_navy.svg
  src/assets/logo/logo_white.svg
  src/layouts/Header/index.tsx
  src/pages/SplashPage/index.tsx
  src/pages/SplashPage/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design, :beers: Chore

#51 ✨ Feat : 포스트 리스트 페이지 마크업 #50
  src/components/PillButtonList/index.tsx
  src/layouts/GlobalLayout/index.tsx
  src/layouts/GlobalNav/style.ts
  src/pages/MateListPage/MateFilterOptions/index.tsx
  src/pages/MateListPage/index.tsx
  src/pages/MateListPage/style.ts
  src/routes/index.tsx
  src/styles/globalStyle.ts
Labels: :sparkles: Feat, :rainbow: Design

#54 🆘 HOTFIX : 로고 변경으로인한 로그인 페이지 경로 오류 수정
  src/pages/LoginPage/index.tsx
Labels: :sos: HOTFIX

#59 ✨ Feat : 굿즈 리스트 페이지 마크업 #58
  src/pages/GoodsListPage/index.tsx
  src/pages/GoodsListPage/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#61 Feat/#60 굿즈 거래 상세페이지 마크업
  src/pages/GoodsDetailPage/index.tsx
  src/pages/GoodsDetailPage/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#62 ✨Feat : 글 작성 페이지 카카오맵 개발 완료 #53
  src/apis/kakaoMapService.ts
  src/components/SubmitPage/index.tsx
  src/hooks/.gitkeep
  src/hooks/useDebounce.ts
  src/hooks/useSearchMap.ts
  src/pages/GoodsPostingPage/Tabs/SecondTab/KakaoMap/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/ResultCard/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/ResultCard/style.ts
  src/pages/GoodsPostingPage/Tabs/SecondTab/ResultList/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/ResultList/style.ts
  src/pages/GoodsPostingPage/Tabs/SecondTab/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/style.ts
Labels: :sparkles: Feat

#55 Feat/#48 메인 페이지
  src/pages/MainPage/GoodsCardSection/index.tsx
  src/pages/MainPage/GoodsCardSection/style.ts
  src/pages/MainPage/MatchUpSection/index.tsx
  src/pages/MainPage/MatchUpSection/style.ts
  src/pages/MainPage/MateCardSection/index.tsx
  src/pages/MainPage/MateCardSection/style.ts
  src/pages/MainPage/RankingSection/index.tsx
  src/pages/MainPage/RankingSection/style.ts
  src/pages/MainPage/index.tsx
  src/pages/MainPage/style.ts
  src/routes/index.tsx
  src/utils/kboInfo.tsx
Labels: :sparkles: Feat, :rainbow: Design

#65 Feat/#56 마이팀 페이지 마크업
  src/components/ScrollToTopButton/index.tsx
  src/components/ScrollToTopButton/style.ts
  src/pages/MyTeamPage/GoodsCardSection/index.tsx
  src/pages/MyTeamPage/GoodsCardSection/style.ts
  src/pages/MyTeamPage/MatchUpSection/index.tsx
  src/pages/MyTeamPage/MatchUpSection/style.ts
  src/pages/MyTeamPage/MateCardSection/index.tsx
  src/pages/MyTeamPage/MateCardSection/style.ts
  src/pages/MyTeamPage/ResultSection/ResultList/index.tsx
  src/pages/MyTeamPage/ResultSection/ResultList/style.ts
  src/pages/MyTeamPage/ResultSection/ResultSummary/index.tsx
  src/pages/MyTeamPage/ResultSection/ResultSummary/style.ts
  src/pages/MyTeamPage/ResultSection/index.tsx
  src/pages/MyTeamPage/ResultSection/style.ts
  src/pages/MyTeamPage/index.tsx
  src/pages/MyTeamPage/style.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#67 💄 Design : CSS 전체 조정 #66
  src/components/MateCard/index.tsx
  src/components/MateCard/style.ts
  src/components/ProfileBedge/style.ts
  src/components/SubmitPage/style.ts
  src/components/UserInfoList/index.tsx
  src/pages/ChatPage/ChatCard/index.tsx
  src/pages/ChatPage/ChatCard/style.ts
  src/pages/ChatPage/style.ts
  src/pages/ChatRoom/ChatCard/index.tsx
  src/pages/ChatRoom/ChatInput/style.ts
  src/pages/ChatRoom/index.tsx
  src/pages/ChatRoom/style.ts
  src/pages/FollowPage/FollowBox/index.tsx
  src/pages/FollowPage/index.tsx
  src/pages/FollowPage/style.ts
  src/pages/GoodsRecordPage/GoodsRecordBox/index.tsx
  src/pages/GoodsRecordPage/style.ts
  src/pages/LoginPage/style.ts
  src/pages/MainPage/MatchUpSection/style.ts
  src/pages/MainPage/RankingSection/style.ts
  src/pages/MainPage/index.tsx
  src/pages/MateDetailPage/MateDetailCard/style.ts
  src/pages/MateDetailPage/style.ts
  src/pages/MateListPage/style.ts
  src/pages/MatePostingPage/Tabs/FirstTab/style.ts
  src/pages/MyTeamPage/MatchUpSection/style.ts
  src/pages/MyTeamPage/ResultSection/ResultList/style.ts
  src/pages/MyTeamPage/style.ts
  src/pages/ProfilePage/ProfileMain.tsx
  src/pages/ProfilePage/style.ts
  src/pages/ReviewWritePage/index.tsx
  src/pages/ReviewWritePage/style.ts
  src/routes/index.tsx
  src/styles/globalStyle.ts
Labels: :rainbow: Design

#70 Feat/#68 타임라인 페이지 기능구현
  package-lock.json
  package.json
  src/pages/TimelinePage/TimelineBox/index.tsx
  src/pages/TimelinePage/TimelineBoxBottom/index.tsx
  src/pages/TimelinePage/index.tsx
  src/pages/TimelinePage/methods.tsx
  src/pages/TimelinePage/mockData.ts
  src/pages/TimelinePage/style.ts
  src/pages/TimelinePage/types.ts
Labels: :sparkles: Feat

#72 ✨ Feat : 리뷰 작성 페이지 컴포넌트화, 리뷰 작성 폼 데이터 정립 #71
  src/pages/ReviewWritePage/ReviewPostInfo/index.tsx
  src/pages/ReviewWritePage/ReviewSelectBox/index.tsx
  src/pages/ReviewWritePage/ReviewTextarea/index.tsx
  src/pages/ReviewWritePage/index.tsx
  src/pages/ReviewWritePage/ratingData.tsx
  src/pages/ReviewWritePage/style.ts
Labels: :sparkles: Feat

#74 ✨ Feat : 리뷰 페이지 props 기반 렌더링 & 리뷰 타입별 구분 #73
  src/hooks/useFormattingDate.ts
  src/pages/ProfilePage/ReviewPage.tsx
  src/pages/ProfilePage/mockData.ts
Labels: :sparkles: Feat

#76 Feat/#69 네이버 로그인
  src/pages/LoginPage/AuthCallback/RedirectHandler.tsx
  src/pages/LoginPage/AuthCallback/RedirectHandlerOld.tsx
  src/pages/LoginPage/NaverLoginButton/index.tsx
  src/routes/index.tsx
Labels: :sparkles: Feat

#79 ✨ Feat : 굿즈 작성 페이지 기능 개발완료
  src/components/ImageInput/index.tsx
  src/components/ImageInput/style.ts
  src/components/ProgressSection/index.tsx
  src/components/ProgressSection/style.ts
  src/components/SubmitPage/index.tsx
  src/components/SubmitPage/style.ts
  src/hooks/useDropDownMenu.ts
  src/hooks/useImageChange.ts
  src/hooks/useInput.ts
  src/hooks/useLocationSearch.ts
  src/hooks/useTabs.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/CategorySection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/CategorySection/style.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/DescriptionSection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/DescriptionSection/style.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/ImageSection/ImageCard/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/ImageSection/ImageCard/style.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/ImageSection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/ImageSection/style.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/PriceInputSection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/PriceInputSection/style.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/ProductNameSection/Index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/ProductNameSection/style.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/TeamSelectSection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/TeamSelectSection/style.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/index.tsx
  src/pages/GoodsPostingPage/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/style.ts
  src/store/useGoodsFormStore.ts
  src/typings/db.ts
  src/typings/model/GoodsModel.ts
  src/utils/tabModel.ts
Labels: :sparkles: Feat

#82 🐛 Fix : 캐릭터 이미지 크기 조절로 용량 축소
  src/assets/character/character-best.svg
  src/assets/character/character-normal.svg
  src/assets/character/character-worst.svg
Labels: :bug: Fix

#87 ✨ Feat : 챗룸 컴포넌트 스플리팅 및 상태관리 개발 완료
  src/components/Alert/index.tsx
  src/components/ProfileBedge/index.tsx
  src/components/TeamSelectSection/index.tsx
  src/constants/alertMessage.ts
  src/constants/kboInfo.tsx
  src/hooks/useModal.ts
  src/pages/ChatPage/index.tsx
  src/pages/ChatRoom/ChatCard/index.tsx
  src/pages/ChatRoom/ChatCard/style.ts
  src/pages/ChatRoom/ChatInput/index.tsx
  src/pages/ChatRoom/Rooms/GeneralChatRoom/GeneralModalContent/index.tsx
  src/pages/ChatRoom/Rooms/GeneralChatRoom/GeneralUserCard/index.tsx
  src/pages/ChatRoom/Rooms/GeneralChatRoom/index.tsx
  src/pages/ChatRoom/Rooms/GoodsChatRoom/GoodsModalContent/index.tsx
  src/pages/ChatRoom/Rooms/GoodsChatRoom/GoodsUserCard/index.tsx
  src/pages/ChatRoom/Rooms/GoodsChatRoom/GoodsUserCard/style.ts
  src/pages/ChatRoom/Rooms/GoodsChatRoom/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/MateModalContent/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/MateUserCard/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/MateUserCard/style.ts
  src/pages/ChatRoom/Rooms/MateChatRoom/RecruitStatusSection/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/index.tsx
  src/pages/ChatRoom/Rooms/UserListSection/index.tsx
  src/pages/ChatRoom/index.tsx
  src/pages/ChatRoom/style.ts
  src/pages/MainPage/GoodsCardSection/index.tsx
  src/pages/MainPage/MatchUpSection/index.tsx
  src/pages/MainPage/MateCardSection/index.tsx
  src/pages/MainPage/RankingSection/index.tsx
  src/pages/MyTeamPage/GoodsCardSection/index.tsx
  src/pages/MyTeamPage/MatchUpSection/index.tsx
  src/pages/MyTeamPage/MateCardSection/index.tsx
  src/pages/MyTeamPage/ResultSection/ResultList/index.tsx
  src/pages/MyTeamPage/ResultSection/ResultSummary/index.tsx
  src/pages/MyTeamPage/ResultSection/ResultSummary/style.ts
  src/store/useGoodsChatStore.ts
  src/store/useMateChatStore.ts
  src/utils/alertMessage.ts
  tsconfig.json
  vite.config.ts
Labels: :sparkles: Feat

#83 PP / 프로필 수정 페이지 기능개발
  src/pages/ProfilePage/BottomModalOption/index.tsx
  src/pages/ProfilePage/BottomModalOption/style.ts
  src/pages/ProfilePage/ProfileEdit.tsx
  src/pages/ProfilePage/methods.ts
  src/pages/ProfilePage/style.ts
Labels: :sparkles: Feat
