Repository prgrms-web-devcourse-final-project/WEB1_2_PitchingMate_FE, pull requests merged in 2024-12, with the labels that each got.

#91 ✨ Feat : 메이트 구인 작성 페이지 첫번째 탭 기능개발 완료 #80
  package-lock.json
  package.json
  src/apis/matchService.ts
  src/apis/queryClient.ts
  src/components/SubmitPage/index.tsx
  src/constants/kboInfo.tsx
  src/hooks/useLocationSearch.ts
  src/hooks/useModal.ts
  src/hooks/useTabs.ts
  src/hooks/useTeamDialog.ts
  src/hooks/useWeeklyMatch.ts
  src/layouts/SubLayout/index.tsx
  src/pages/GoodsPostingPage/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/BottomModalOption/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/BottomModalOption/style.ts
  src/pages/MatePostingPage/Tabs/FirstTab/GameButtonList/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/GameList/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/GameListCard/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/mockdata.ts
  src/pages/MatePostingPage/Tabs/SecondTab/SelectOption/index.tsx
  src/pages/MatePostingPage/Tabs/SecondTab/SelectOption/style.ts
  src/pages/MatePostingPage/Tabs/SecondTab/index.tsx
  src/pages/MatePostingPage/index.tsx
  src/pages/MatePostingPage/style.ts
  src/store/useGoodsFormStore.ts
  src/store/useMateFormStore.ts
  src/styles/globalStyle.ts
  src/typings/.gitkeep
  src/typings/db.ts
  src/utils/Model/GoodsModel.ts
  src/utils/Model/matePostModel.ts
  src/utils/Model/tabModel.ts
  src/utils/formatDate.ts
  src/utils/formatTeamName.ts
Labels: :sparkles: Feat

#90 글로벌 네비게이션 기능개발
  src/constants/ROUTE_PATH.tsx
  src/layouts/GlobalNav/index.tsx
  src/routes/index.tsx
Labels: :sparkles: Feat

#93 서브헤더 컴포넌트화 & 페이지별 적용
  src/layouts/SubHeader/index.tsx
  src/layouts/SubHeader/style.ts
  src/layouts/SubLayout/index.tsx
  src/pages/ChatPage/index.tsx
  src/pages/ChatRoom/index.tsx
  src/pages/FollowPage/index.tsx
  src/pages/GoodsDetailPage/index.tsx
  src/pages/GoodsPostingPage/index.tsx
  src/pages/GoodsRecordPage/index.tsx
  src/pages/MateDetailPage/index.tsx
  src/pages/ProfilePage/ProfileEdit.tsx
  src/pages/ProfilePage/ProfileMain.tsx
  src/pages/ProfilePage/ReviewPage.tsx
  src/styles/globalStyle.ts
Labels: :sparkles: Feat

#94 Feat/#75 굿즈 거래 기록 페이지 기능개발
  src/pages/GoodsRecordPage/GoodsRecordBox/index.tsx
  src/pages/GoodsRecordPage/index.tsx
  src/pages/GoodsRecordPage/mockData.ts
Labels: :sparkles: Feat

#97 ✨ Feat : 메이트 포스트 생성 처리 완료
  src/apis/matchService.ts
  src/apis/matePostService.ts
  src/apis/queryClient.ts
  src/components/ImageInput/index.tsx
  src/hooks/useCategoryState.ts
  src/hooks/useImageChange.ts
  src/hooks/usePostMatePost.ts
  src/hooks/useSubmitMatePost.ts
  src/hooks/useWeeklyMatch.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/ImageSection/ImageCard/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/ImageSection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/TeamSelectSection/index.tsx
  src/pages/MatePostingPage/Tabs/SecondTab/SelectOption/index.tsx
  src/pages/MatePostingPage/Tabs/SecondTab/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/InputSection/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/TextAreaSection/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/imageSection/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/style.ts
  src/pages/MatePostingPage/index.tsx
  src/store/useGoodsFormStore.ts
  src/store/useMateFormStore.ts
  src/typings/db.ts
Labels: :sparkles: Feat

#102 ✨ Feat : 메인 페이지 Swiper 오토 플레이 추가 #101
  src/pages/MainPage/MatchUpSection/index.tsx
Labels: :sparkles: Feat

#100 FIX / 프로필 페이지 링크 수정 & 리뷰 페이지 접속 오류 해결
  src/pages/GoodsRecordPage/index.tsx
  src/pages/ProfilePage/ProfileMain.tsx
  src/pages/ProfilePage/ReviewPage.tsx
  src/pages/ProfilePage/mockData.ts
  src/pages/TimelinePage/index.tsx
  src/styles/globalStyle.ts
Labels: :sparkles: Feat

#107 ✨ Feat : 굿즈 거래 포스팅 API 연동 및 상태관리 zustand로 변경 처리 완료 #98
  src/apis/goodsPostService.ts
  src/hooks/useImageChange.ts
  src/hooks/useLocationSearch.ts
  src/hooks/usePostGoodsPost.ts
  src/hooks/useSubmitGoodsPost.ts
  src/hooks/useSubmitMatePost.ts
  src/hooks/useTeamDialog.ts
  src/pages/GoodsPostingPage/Tabs/FirstTab/ImageSection/ImageCard/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/ImageSection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/TeamSelectSection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/KakaoMap/index.tsx
  src/pages/GoodsPostingPage/Tabs/SecondTab/KakaoMap/style.ts
  src/pages/GoodsPostingPage/Tabs/SecondTab/index.tsx
  src/pages/GoodsPostingPage/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/InputSection/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/imageSection/index.tsx
  src/pages/MatePostingPage/index.tsx
  src/pages/ProfilePage/BottomModalOption/index.tsx
  src/store/useGoodsFormStore.ts
  src/store/useMateFormStore.ts
  src/typings/db.ts
  src/typings/postForm.ts
Labels: :sparkles: Feat

#113 💄 Design : 포스팅 페이지 레이아웃 수정 완료
  src/components/ProgressSection/style.ts
  src/pages/MatePostingPage/style.ts
Labels: :rainbow: Design

#104 Feat/#77 메인 페이지 api 연동 설계 일부
  src/apis/queryClient.ts
  src/components/CardBedge/index.tsx
  src/components/CardBedge/style.ts
  src/components/GoodsCard/index.tsx
  src/components/MateCard/index.tsx
  src/components/TeamSelectSection/index.tsx
  src/components/TeamSelectSection/style.ts
  src/pages/MainPage/GoodsCardSection/index.tsx
  src/pages/MainPage/GoodsCardSection/style.ts
  src/pages/MainPage/MatchUpSection/index.tsx
  src/pages/MainPage/MatchUpSection/style.ts
  src/pages/MainPage/MateCardSection/index.tsx
  src/pages/MainPage/MateCardSection/style.ts
  src/pages/MainPage/RankingSection/index.tsx
  src/pages/MainPage/RankingSection/style.ts
  src/pages/MainPage/ResultSection/ResultList/index.tsx
  src/pages/MainPage/ResultSection/ResultList/style.ts
  src/pages/MainPage/ResultSection/ResultSummary/index.tsx
  src/pages/MainPage/ResultSection/ResultSummary/style.ts
  src/pages/MainPage/ResultSection/index.tsx
  src/pages/MainPage/ResultSection/style.ts
  src/pages/MainPage/index.tsx
  src/typings/db.ts
Labels: :sparkles: Feat

#118 Feat/#103 프로필 페이지 스켈레톤 처리 & 프로필 페이지 API 연동
  src/apis/queryClient.ts
  src/apis/userService.ts
  src/hooks/useGetUserInfo.ts
  src/main.tsx
  src/pages/ProfilePage/ProfileMain.tsx
  src/pages/ProfilePage/style.ts
  src/styles/globalStyle.ts
Labels: :sparkles: Feat, :bug: Fix

#121 Feat/#114 굿즈. 메이트 포스트 수정 처리완료
  src/apis/goodsPostService.ts
  src/apis/matePostService.ts
  src/apis/queryClient.ts
  src/hooks/usePostGoodsPost.ts
  src/hooks/usePostMatePost.ts
  src/hooks/useSubmitGoodsPost.ts
  src/hooks/useSubmitMatePost.ts
  src/hooks/useUpdateFormdata.ts
  src/hooks/useUpdateMateFormData.ts
  src/hooks/useWeeklyMatch.ts
  src/hooks/usegetGoodsPost.ts
  src/hooks/usegetMatePost.ts
  src/layouts/SubHeader/index.tsx
  src/pages/GoodsPostingPage/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/GameButtonList/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/GameList/index.tsx
  src/pages/MatePostingPage/index.tsx
  src/routes/index.tsx
  src/store/useGoodsFormStore.ts
  src/store/useMateFormStore.ts
  src/typings/db.ts
  src/utils/formatParticipants.ts
  src/utils/formatPostData.ts
  src/utils/formatPrice.ts
Labels: :sparkles: Feat

#122 Feat/#119 프로필 수정 페이지 기능개발 2
  src/apis/queryClient.ts
  src/apis/userService.ts
  src/hooks/useEditMyInfo.ts
  src/hooks/useGetMyInfo.ts
  src/hooks/useTeamDialog.ts
  src/layouts/SubHeader/index.tsx
  src/layouts/SubHeader/style.ts
  src/pages/ProfilePage/BottomModalOption/index.tsx
  src/pages/ProfilePage/ProfileEdit.tsx
  src/pages/ProfilePage/methods.ts
Labels: :sparkles: Feat

#126 ✨ Feat : 굿즈거래 리스트 페이지 데이터 출력 / 굿즈 거래 디테일 페이지 데이터 출력 / CRUD / 채팅방 개설
  src/apis/goodsChatService.ts
  src/apis/goodsPostService.ts
  src/apis/goodsService.ts
  src/components/Alert/index.tsx
  src/components/BottomModal/index.tsx
  src/components/GoodsCard/index.tsx
  src/components/MateCard/index.tsx
  src/components/TeamSelectSection/index.tsx
  src/components/UserInfoList/index.tsx
  src/constants/ROUTE_PATH.ts
  src/constants/alertMessage.ts
  src/constants/kboInfo.tsx
  src/hooks/usePostGoodsPost.ts
  src/hooks/useUpdateFormdata.ts
  src/hooks/useUpdateMateFormData.ts
  src/pages/GoodsDetailPage/index.tsx
  src/pages/GoodsListPage/index.tsx
  src/pages/GoodsListPage/style.ts
  src/pages/GoodsPostingPage/index.tsx
  src/pages/MateListPage/MateFilterOptions/index.tsx
  src/typings/db.ts
Labels: :sparkles: Feat

#128 PP / 프로필 페이지 & 프로필 수정 페이지 API 조정, 카드 벳지 CSS 수정
  src/components/CardBedge/style.ts
  src/components/MateCard/style.ts
  src/hooks/useEditMyInfo.ts
  src/pages/MateListPage/index.tsx
  src/pages/ProfilePage/ProfileEdit.tsx
  src/pages/ProfilePage/ProfileMain.tsx
  src/pages/ProfilePage/style.ts
  src/typings/userForm.ts
Labels: :sparkles: Feat, :rainbow: Design

#130 ✨ Feat :메이트 상세 페이지 기능 구현 완료
  src/apis/matePostService.ts
  src/components/MateCard/index.tsx
  src/components/MateCard/style.ts
  src/components/UserInfoList/index.tsx
  src/constants/ROUTE_PATH.ts
  src/hooks/usePostGoodsPost.ts
  src/hooks/usePostMatePost.ts
  src/pages/MainPage/MateCardSection/index.tsx
  src/pages/MateDetailPage/MateDetailAction/index.tsx
  src/pages/MateDetailPage/MateDetailCard/index.tsx
  src/pages/MateDetailPage/index.tsx
  src/pages/MateDetailPage/style.ts
  src/pages/MateListPage/index.tsx
  src/pages/MatePostingPage/index.tsx
  src/pages/ProfilePage/BottomModalOption/index.tsx
  src/routes/index.tsx
  src/store/useMateFormStore.ts
  src/utils/formatPostData.ts
Labels: :sparkles: Feat

#132 GD / 긋즈 디테일 페이지 수정사항반영 & 기타 수정사항
  src/assets/icon/back.svg
  src/components/CardBedge/index.tsx
  src/components/UserInfoList/index.tsx
  src/components/UserInfoList/style.ts
  src/layouts/SubHeader/index.tsx
  src/pages/GoodsDetailPage/KakaoMapContainer/index.tsx
  src/pages/GoodsDetailPage/index.tsx
  src/pages/GoodsDetailPage/style.ts
  src/pages/ProfilePage/BottomModalOption/index.tsx
  src/pages/ProfilePage/ProfileEdit.tsx
  src/pages/ProfilePage/ProfileMain.tsx
Labels: :sparkles: Feat, :rainbow: Design, :bug: Fix

#135 메이트 리스트 페이지 API 연동
  src/apis/mateListService.ts
  src/pages/MateListPage/MateFilterOptions/index.tsx
  src/pages/MateListPage/index.tsx
Labels: :sparkles: Feat

#137 R_4 / 리뷰 작성 페이지 기능개발
  src/apis/queryClient.ts
  src/apis/reviewService.ts
  src/pages/GoodsDetailPage/index.tsx
  src/pages/ReviewWritePage/ReviewSelectBox/index.tsx
  src/pages/ReviewWritePage/index.tsx
  src/pages/ReviewWritePage/ratingData.tsx
Labels: :sparkles: Feat

#138 🐛 Fix : 필터 인원 선택시 숫자로 넘어가도록 수정
  src/apis/mateListService.ts
Labels: :bug: Fix

#140 GR / 굿즈 기록 페이지 API 연동
  src/apis/queryClient.ts
  src/apis/userService.ts
  src/pages/GoodsRecordPage/GoodsRecordBox/index.tsx
  src/pages/GoodsRecordPage/index.tsx
  src/pages/GoodsRecordPage/style.ts
  src/pages/MainPage/MatchUpSection/index.tsx
  src/pages/ProfilePage/ProfileMain.tsx
Labels: :sparkles: Feat

#142 TL / 타임라인 API 연동 & 메이트 작성 페이지 CSS 수정
  src/apis/queryClient.ts
  src/apis/reviewService.ts
  src/assets/character/character-best.png
  src/assets/character/character-normal.png
  src/assets/character/character-worst.png
  src/pages/MatePostingPage/Tabs/FirstTab/GameButtonList/style.ts
  src/pages/MatePostingPage/Tabs/FirstTab/GameListCard/index.tsx
  src/pages/MatePostingPage/Tabs/FirstTab/GameListCard/style.ts
  src/pages/TimelinePage/index.tsx
  src/utils/formatDate.ts
Labels: :sparkles: Feat, :rainbow: Design, :bug: Fix

#144 💄 Design : 메인 포스트 카드 페이지 구조 및 CSS 수정 #143
  src/components/MainMateCard/index.tsx
  src/components/MainMateCard/style.ts
  src/pages/MainPage/MateCardSection/index.tsx
Labels: :rainbow: Design

#145 Feat/#136 굿즈, 메이트 포스트 관련 API 체크, 굿즈, 메이트 리스트 무한 스크롤 구현
  src/apis/goodsChatService.ts
  src/apis/goodsPostService.ts
  src/apis/goodsService.ts
  src/apis/mateChatService.ts
  src/apis/mateListService.ts
  src/apis/matePostService.ts
  src/apis/queryClient.ts
  src/components/FloatButton/index.tsx
  src/components/GoodsListCard/index.tsx
  src/components/GoodsListCard/style.ts
  src/hooks/useGoodsChat.ts
  src/hooks/useTopRef.ts
  src/pages/ChatRoom/Rooms/GoodsChatRoom/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/index.tsx
  src/pages/GoodsDetailPage/index.tsx
  src/pages/GoodsListPage/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/DescriptionSection/index.tsx
  src/pages/GoodsPostingPage/Tabs/FirstTab/ProductNameSection/Index.tsx
  src/pages/MainPage/MatchUpSection/index.tsx
  src/pages/MateListPage/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/InputSection/index.tsx
  src/pages/MatePostingPage/Tabs/ThirdTab/TextAreaSection/index.tsx
  src/pages/ProfilePage/ProfileEdit.tsx
  src/styles/globalStyle.ts
  src/utils/formatPostData.ts
Labels: :sparkles: Feat

#154 굿즈 기록 페이지 기능 개발 & 일부 페이지 CSS 수정
  src/apis/userService.ts
  src/components/MainMateCard/style.ts
  src/components/Spinner/index.tsx
  src/components/Spinner/style.ts
  src/components/TeamSelectSection/style.ts
  src/pages/GoodsRecordPage/GoodsRecordBox/index.tsx
  src/pages/GoodsRecordPage/index.tsx
  src/pages/GoodsRecordPage/style.ts
  src/pages/MateListPage/index.tsx
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design

#151 ✨ Feat : 후기 페이지 API 연동 & 무한스크롤 기능구현 #147
  src/apis/queryClient.ts
  src/apis/reviewService.ts
  src/pages/ProfilePage/ReviewBoxComponent/index.tsx
  src/pages/ProfilePage/ReviewPage.tsx
  src/typings/reviewPage.ts
  src/utils/formatDate.ts
Labels: :sparkles: Feat

#157 Feat/#106 로그인 및 회원가입 API 연동
  src/apis/loginService.ts
  src/components/Form/index.tsx
  src/components/GlobalButton/index.tsx
  src/components/GlobalButton/style.ts
  src/components/TeamSelectModal/index.tsx
  src/constants/ROUTE_PATH.ts
  src/pages/LoginPage/AuthCallback/NaverCallback.tsx
  src/pages/LoginPage/AuthCallback/RedirectHandler.tsx
  src/pages/LoginPage/AuthCallback/RedirectHandlerOld.tsx
  src/pages/LoginPage/NaverLoginButton/index.tsx
  src/pages/LoginPage/SignupPage/index.tsx
  src/pages/LoginPage/index.tsx
  src/routes/index.tsx
  src/typings/db.ts
Labels: :sparkles: Feat

#164 FEAT : 배포 과정에서의 env 추가
  .github/workflows/deploy.yml
Labels: :sparkles: Feat

#165 타임라인 접근 메이트 직관 후기 작성 기능개발
  src/apis/queryClient.ts
  src/apis/reviewService.ts
  src/hooks/useReviewHooks.ts
  src/pages/GoodsDetailPage/GoodsHostButton/index.tsx
  src/pages/GoodsDetailPage/GoodsVisitorButton/index.tsx
  src/pages/GoodsDetailPage/index.tsx
  src/pages/GoodsDetailPage/style.ts
  src/pages/GoodsRecordPage/index.tsx
  src/pages/ReviewWritePage/ReviewPostInfo/index.tsx
  src/pages/ReviewWritePage/ReviewSelectBox/index.tsx
  src/pages/ReviewWritePage/index.tsx
  src/pages/ReviewWritePage/ratingData.tsx
  src/pages/ReviewWritePage/style.ts
  src/pages/TimelinePage/TimelineBox/index.tsx
  src/pages/TimelinePage/TimelineBoxBottom/index.tsx
  src/pages/TimelinePage/index.tsx
  src/pages/TimelinePage/methods.tsx
  src/pages/TimelinePage/style.ts
  src/pages/TimelinePage/types.ts
  src/routes/index.tsx
Labels: :sparkles: Feat, :rainbow: Design, :bug: Fix

#166 Feat/#148 메인 페이지 팀 선택 문제 해결 및 기타
  src/components/TeamSelectSection/index.tsx
  src/components/TeamSelectSection/style.ts
  src/constants/kboInfo.tsx
  src/layouts/Header/index.tsx
  src/pages/MainPage/GoodsCardSection/index.tsx
  src/pages/MainPage/MatchUpSection/index.tsx
  src/pages/MainPage/MateCardSection/index.tsx
  src/pages/MainPage/RankingSection/index.tsx
  src/pages/MainPage/ResultSection/ResultList/index.tsx
  src/pages/MainPage/ResultSection/ResultSummary/index.tsx
  src/pages/MainPage/ResultSection/ResultSummary/style.ts
  src/pages/MainPage/ResultSection/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MateListPage/MateFilterOptions/index.tsx
Labels: :sparkles: Feat, :bug: Fix, :speech_balloon: Comment

#168 🐛 Fix : 굿즈 기록 무한반복 버그 수정 #167
  src/apis/userService.ts
Labels: :bug: Fix

#177 🐛 Fix : 완료 버튼에 필터 적용되도록 적용
  src/pages/MateListPage/index.tsx
Labels: :bug: Fix

#178 메이트 상세 페이지 버튼 표시 조건 마크업 및 안내 문구 위치 조절
  src/pages/MateDetailPage/MateDetailAction/index.tsx
  src/pages/MateDetailPage/MateDetailAction/style.ts
  src/pages/MateDetailPage/style.ts
Labels: :sparkles: Feat, :rainbow: Design

#180 ✨ Feat : 로그아웃 기능 연동
  src/apis/logoutService.ts
  src/layouts/SubHeader/index.tsx
  src/pages/ProfilePage/ProfileMain.tsx
Labels: :sparkles: Feat

#173 프로필 하위 페이지 무한스크롤 수정 및 기타 수정
  src/apis/reviewService.ts
  src/apis/userService.ts
  src/components/MainMateCard/style.ts
  src/components/Spinner/style.ts
  src/layouts/SubHeader/index.tsx
  src/layouts/SubHeader/style.ts
  src/pages/GoodsRecordPage/index.tsx
  src/pages/MainPage/style.ts
  src/pages/ProfilePage/ReviewPage.tsx
  src/pages/TimelinePage/TimelineBox/index.tsx
  src/pages/TimelinePage/index.tsx
  src/styles/globalStyle.ts
Labels: :rainbow: Design, :bug: Fix, :beers: Chore

#181 로그인 정보 store 저장 & 프로필 하위 페이지 API 충돌 제거
  package-lock.json
  package.json
  src/apis/loginService.ts
  src/hooks/useEditMyInfo.ts
  src/layouts/GlobalNav/index.tsx
  src/main.tsx
  src/pages/GoodsRecordPage/index.tsx
  src/pages/ProfilePage/ProfileEdit.tsx
  src/pages/ProfilePage/ProfileMain.tsx
  src/pages/ProfilePage/ReviewBoxComponent/index.tsx
  src/pages/ProfilePage/ReviewPage.tsx
  src/pages/ProfilePage/style.ts
  src/routes/index.tsx
  src/store/useUserStore.ts
Labels: :sparkles: Feat, :bug: Fix

#189 로그인 정보 로컬스토리지 저장 및 이에 따른 프로필 하위페이지 수정
  src/apis/reviewService.ts
  src/hooks/useEditMyInfo.ts
  src/hooks/useGetMyInfo.ts
  src/hooks/useReviewHooks.ts
  src/layouts/GlobalNav/index.tsx
  src/pages/GoodsDetailPage/index.tsx
  src/pages/GoodsRecordPage/index.tsx
  src/pages/GoodsRecordPage/style.ts
  src/pages/ProfilePage/ProfileEdit.tsx
  src/pages/ProfilePage/ProfileMain.tsx
  src/pages/ProfilePage/ReviewBoxComponent/index.tsx
  src/pages/ProfilePage/ReviewPage.tsx
  src/pages/ProfilePage/style.ts
  src/pages/ReviewWritePage/ReviewPostInfo/index.tsx
  src/pages/ReviewWritePage/index.tsx
  src/utils/formatManner.ts
Labels: :sparkles: Feat, :rainbow: Design, :bug: Fix, :beers: Chore

#190 Feat/#186 회원 탈퇴 기능 연동
  src/apis/unregisterService.ts
  src/constants/alertMessage.ts
  src/layouts/GlobalNav/index.tsx
  src/pages/ProfilePage/ProfileMain.tsx
Labels: :sparkles: Feat

#191 메이트 디테일 페이지
  src/apis/loginService.ts
  src/apis/matePostService.ts
  src/pages/MateDetailPage/MateDetailAction/index.tsx
  src/typings/db.ts
Labels: :sparkles: Feat

#192 ✨Feat : 메이트 채팅방 동작 처리
  package-lock.json
  package.json
  src/apis/mateChatService.ts
  src/hooks/useChatExit.ts
  src/hooks/useCompleteMate.ts
  src/hooks/useCreateChatRoom.ts
  src/hooks/useNavigatChatRoom.ts
  src/hooks/useSocket.ts
  src/layouts/SubLayout/index.tsx
  src/pages/ChatPage/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/MateModalContent/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/MateUserCard/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/index.tsx
  src/pages/ChatRoom/index.tsx
  src/pages/ChatRoom/style.ts
  src/store/useMateChatStore.ts
Labels: :sparkles: Feat

#195 🐛 keepPreviousData로 리렌더링 문제 해결
  src/pages/GoodsListPage/index.tsx
  src/pages/MateListPage/index.tsx
Labels: :bug: Fix

#196 FIX / 기타 수정사항
  src/pages/GoodsDetailPage/index.tsx
  src/pages/GoodsListPage/style.ts
  src/pages/ProfilePage/ProfileMain.tsx
Labels: :rainbow: Design, :bug: Fix

#198 🐛 Fix : 디테일 페이지 유저 리스트 점수 소숫점 포맷팅 추가 #197
  src/components/UserInfoList/index.tsx
Labels: :bug: Fix

#200 ✨ Feat : 채팅방 동작 처리완료
  src/apis/goodsChatService.ts
  src/apis/goodsPostService.ts
  src/components/GoodsListCard/index.tsx
  src/components/GoodsListCard/style.ts
  src/hooks/useChatExit.ts
  src/hooks/useCompletePost.ts
  src/hooks/useCreateChatRoom.ts
  src/pages/ChatPage/ChatCard/style.ts
  src/pages/ChatRoom/ChatInput/index.tsx
  src/pages/ChatRoom/ChatInput/style.ts
  src/pages/ChatRoom/Rooms/GoodsChatRoom/GoodsChatInput/index.tsx
  src/pages/ChatRoom/Rooms/GoodsChatRoom/GoodsModalContent/index.tsx
  src/pages/ChatRoom/Rooms/GoodsChatRoom/GoodsUserCard/index.tsx
  src/pages/ChatRoom/Rooms/GoodsChatRoom/GoodsUserCard/style.ts
  src/pages/ChatRoom/Rooms/GoodsChatRoom/index.tsx
  src/pages/ChatRoom/Rooms/MateChatRoom/index.tsx
  src/pages/ChatRoom/style.ts
  src/store/useGoodsChatStore.ts
  src/typings/db.ts
  src/typings/mateChat.ts
Labels: :sparkles: Feat

#201 Feat/#199 로딩 시 min-height 추가 및 smooth 삭제
  src/components/ScrollToTopButton/index.tsx
  src/components/TeamSelectSection/index.tsx
  src/hooks/useTopRef.ts
  src/pages/GoodsListPage/style.ts
  src/pages/MainPage/GoodsCardSection/index.tsx
  src/pages/MainPage/GoodsCardSection/style.ts
  src/pages/MainPage/MatchUpSection/index.tsx
  src/pages/MainPage/MatchUpSection/style.ts
  src/pages/MainPage/MateCardSection/index.tsx
  src/pages/MainPage/MateCardSection/style.ts
  src/pages/MainPage/RankingSection/index.tsx
  src/pages/MainPage/RankingSection/style.ts
  src/pages/MainPage/ResultSection/ResultList/index.tsx
  src/pages/MainPage/ResultSection/ResultList/style.ts
  src/pages/MainPage/ResultSection/ResultSummary/index.tsx
  src/pages/MainPage/ResultSection/ResultSummary/style.ts
  src/pages/MateListPage/index.tsx
  src/pages/MateListPage/style.ts
Labels: :rainbow: Design, :bug: Fix

#203 ✨ Feat : 로그인 상태일 때 마이팀 자동 선택 기능 추가
  src/pages/GoodsListPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MateListPage/index.tsx
Labels: :sparkles: Feat

#206 📝 Docs : README.md 작성
  README.md
Labels: :memo: Docs

#208 Docs/#207 워크플로우 문서 수정
  .github/workflows/deploy.yml
  README.md
  src/apis/loginService.ts
  src/pages/LoginPage/SignupPage/index.tsx
Labels: :memo: Docs, :speech_balloon: Comment
